In [1]:
import torch

if torch.cuda.is_available():
    device = "cuda"  # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps"  # Apple Silicon GPU
else:
    device = "cpu"  # Fallback to CPU
print(f"Using device: {device}")

Using device: cuda


In [3]:
# Dataset: rows are samples (N), columns are features (D)
dataset = torch.tensor([
    [0.12, 0.30, -0.02],
    [0.15, 0.28, -0.01],
    [0.08, 0.35, -0.03],
    [0.10, 0.25, -0.01]
], device=device)

# Combinations: thresholds for each feature (C x D)
combinations = torch.tensor([
    [0.10, 0.25, -0.01], 
    [0.15, 0.30, -0.02]
], device=device)

In [ ]:
# Expand dimensions for broadcasting
dataset_expanded = dataset.unsqueeze(1)               # Shape: [N x 1 x D]
combinations_expanded = combinations.unsqueeze(0)     # Shape: [1 x C x D]

# Compute masks for long and short conditions
long_mask = dataset_expanded > combinations_expanded          # Long condition mask
short_mask = dataset_expanded < (1 - combinations_expanded)   # Short condition mask

# Select appropriate mask based on condition types # Shape: [1 x 1 x D]
masks = torch.where(condition_types_expanded == 1, long_mask, short_mask)   # Shape: [N x C x D]

# Combine masks across features using logical AND along feature dimension
row_combination_masks = masks.all(dim=2)   # Shape: [N x C]

print("Row-Combination Masks:")
print(row_combination_masks)

In [31]:
from scipy import stats

x1 = torch.normal(mean=0, std=0.3, size=(10, 1))
x2 = torch.minimum(torch.abs(torch.normal(mean=0.25, std=0.2, size=(10, 1))), torch.tensor(1.0))

In [33]:
combs_1 = torch.arange(-1.0, 1.0, step=0.1)
combs_2 = torch.arange(0.0, 1.0, step=0.1)

In [32]:
x2

tensor([[0.3739],
        [0.3366],
        [0.2445],
        [0.4173],
        [0.3279],
        [0.2930],
        [0.1878],
        [0.6757],
        [0.2247],
        [0.0508]])

In [28]:
x1 > combs

tensor([[False, False, False, False, False, False, False, False, False, False],
        [ True, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False, False, False],
        [ True, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [37]:
combs = torch.meshgrid([combs_1, combs_2])

In [42]:
combs[0][0]

tensor([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [45]:
combs = torch.stack(combs, dim=-1)

In [46]:
x1 > combs.dim()

tensor([[[-1.0000e+00,  0.0000e+00],
         [-1.0000e+00,  1.0000e-01],
         [-1.0000e+00,  2.0000e-01],
         [-1.0000e+00,  3.0000e-01],
         [-1.0000e+00,  4.0000e-01],
         [-1.0000e+00,  5.0000e-01],
         [-1.0000e+00,  6.0000e-01],
         [-1.0000e+00,  7.0000e-01],
         [-1.0000e+00,  8.0000e-01],
         [-1.0000e+00,  9.0000e-01]],

        [[-9.0000e-01,  0.0000e+00],
         [-9.0000e-01,  1.0000e-01],
         [-9.0000e-01,  2.0000e-01],
         [-9.0000e-01,  3.0000e-01],
         [-9.0000e-01,  4.0000e-01],
         [-9.0000e-01,  5.0000e-01],
         [-9.0000e-01,  6.0000e-01],
         [-9.0000e-01,  7.0000e-01],
         [-9.0000e-01,  8.0000e-01],
         [-9.0000e-01,  9.0000e-01]],

        [[-8.0000e-01,  0.0000e+00],
         [-8.0000e-01,  1.0000e-01],
         [-8.0000e-01,  2.0000e-01],
         [-8.0000e-01,  3.0000e-01],
         [-8.0000e-01,  4.0000e-01],
         [-8.0000e-01,  5.0000e-01],
         [-8.0000e-01,  6.0000e-01

In [50]:
x1_expanded = x1.unsqueeze(1)

In [51]:
x1_expanded.shape

torch.Size([10, 1, 1])

In [57]:
combs[:, :, 0]

tensor([[-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00],
        [-9.0000e-01, -9.0000e-01, -9.0000e-01, -9.0000e-01, -9.0000e-01,
         -9.0000e-01, -9.0000e-01, -9.0000e-01, -9.0000e-01, -9.0000e-01],
        [-8.0000e-01, -8.0000e-01, -8.0000e-01, -8.0000e-01, -8.0000e-01,
         -8.0000e-01, -8.0000e-01, -8.0000e-01, -8.0000e-01, -8.0000e-01],
        [-7.0000e-01, -7.0000e-01, -7.0000e-01, -7.0000e-01, -7.0000e-01,
         -7.0000e-01, -7.0000e-01, -7.0000e-01, -7.0000e-01, -7.0000e-01],
        [-6.0000e-01, -6.0000e-01, -6.0000e-01, -6.0000e-01, -6.0000e-01,
         -6.0000e-01, -6.0000e-01, -6.0000e-01, -6.0000e-01, -6.0000e-01],
        [-5.0000e-01, -5.0000e-01, -5.0000e-01, -5.0000e-01, -5.0000e-01,
         -5.0000e-01, -5.0000e-01, -5.0000e-01, -5.0000e-01, -5.0000e-01],
        [-4.0000e-01, -4.0000e-01, -4.0000e-01, -4.0000e-01, -4.0000e-01,
         -4.0000e-01, -4.0000e-0